chnages, edits and syles
tic-oss/wda-ui pull request #81
Opened 2023-07-27 06:52 UTC by HarikaSree22

2023-07-27 09:49 UTC, craxkumar commented on src/App.css
> +.react-flow__node.react-flow__node-customnode,
this is the customnode added by @dheerajsai-g  for testing purpose 
i have asked him to remove it,
i give u missed this one to remove
please remove it!

2023-07-27 09:51 UTC, craxkumar commented on src/components/Sidebar.js
> +          {/* {isEmptyUiSubmit === true ? (
u can remove the commented code!
good practises

2023-07-27 09:52 UTC, craxkumar requested changes
Please resolve the  review comments

2023-07-27 10:14 UTC, HarikaSree22 commented on src/App.css
> +.react-flow__node.react-flow__node-customnode,
DONE

2023-07-27 10:14 UTC, HarikaSree22 commented on src/components/Sidebar.js
> +          {/* {isEmptyUiSubmit === true ? (
done

2023-07-27 10:43 UTC, craxkumar approved these changes
Review OK!

2023-07-28 06:05 UTC, rohithteja-cmi approved these changes

2023-07-28 06:05 UTC, merged