Fix/edit
tic-oss/wda-ui pull request #83
Opened 2023-08-11 04:53 UTC by Sri-Harsha06

2023-08-14 06:35 UTC, craxkumar requested changes

2023-08-14 06:35 UTC, craxkumar commented on src/pages/Designer.js
> +      console.log("hiiiiiiiii",updatedNodes);
remove log

2023-08-14 06:35 UTC, craxkumar commented on src/pages/Designer.js
> +      Data.serverPort = Data.serverPort.trim();
not required!

2023-08-14 06:35 UTC, craxkumar commented on src/pages/Designer.js
>      console.log(Data, "Finaaal Dataaaaaaaaaa");
remove this

2023-08-21 13:22 UTC, rohithteja-cmi approved these changes

2023-08-21 13:23 UTC, merged