- Save state on refresh for edit and create page using localStorage
tic-oss/wda-ui pull request #89
Opened 2023-08-29 13:43 UTC by Sri-Harsha06

- Modified Nav included new and existingprojects in canvastocode tab
- Alert Dialog for user before going to new project while in canvas or before deleting project
- Save state on refresh for project page
- Validation Checks for appName UI and Service

2023-08-30 05:33 UTC, craxkumar commented on src/components/Modal/ActionModal.js
> +                Leaving this page will result in lost unsaved changes. Would you
change lost to loss

2023-08-30 05:33 UTC, craxkumar commented on src/components/Modal/UIModal.js
> +  // const appNameCheck = !/^[a-zA-Z](?:[a-zA-Z0-9_]*[a-zA-Z0-9])?$/g.test(
remove the commented code if not required!

2023-08-30 05:33 UTC, craxkumar commented on src/components/Modal/ServiceModal.js
> +  // const appNameCheck = /[0-9_-]/.test(ApplicationData.applicationName);
remove the commented code if not required!

2023-08-30 05:33 UTC, craxkumar commented on src/pages/Designer.js
>      console.log(Data, "Finaaal Dataaaaaaaaaa");
remove the comments !

2023-08-30 05:50 UTC, HarikaSree22 commented on src/components/Modal/ActionModal.js
> +                Leaving this page will result in lost unsaved changes. Would you
Navigating away from this page without saving will lead to the loss of any unsaved changes.

2023-08-31 08:11 UTC, craxkumar commented on src/components/Modal/DeployModal.js
> +      if (Object.keys(DeploymentData) !== 0)
at max try to write the positive case condition 
for example 
 if (Object.keys(DeploymentData) !== 0) this can be 
  if (Object.keys(DeploymentData) === 1) right ?
  as there is always one DeploymentData.

just a good practise ntg wrong !

2023-08-31 08:21 UTC, craxkumar requested changes

2023-08-31 08:21 UTC, craxkumar commented on src/components/Modal/UIModal.js
> +                  Application Name should not contain -, _ or number.
numbers.

2023-08-31 08:21 UTC, craxkumar commented on src/components/Navbar.js
> +          {/* {initialized && keycloak.authenticated && (
if this not really required you remove, 
if you think this can be used in the future for some or the other reason 
please ignore the comment

2023-08-31 08:21 UTC, craxkumar commented on src/pages/Project.js
> +      let datastorage = JSON.parse(localStorage.getItem("data"));
datastorage 
Please follow camelCase.

2023-08-31 08:21 UTC, craxkumar commented on src/pages/Project.js
>        setmetadata(data.metadata);
setmetadata

should be setMetadata 

Please change if it ohk to change as it is not done by you 
if doable please make the changes else you can leave it.

2023-08-31 08:21 UTC, craxkumar commented on src/pages/Project.js
> +    if (!(Object.keys(val).length === 0))
check if this can be changed to positive condition 
if (!(Object.keys(val).length === 0)) instead 

if ((Object.keys(val).length >= 1))

why we say to positive condition is 
it increases the readability

2023-08-31 10:17 UTC, craxkumar approved these changes
Review OK!

2023-08-31 10:24 UTC, rohithteja-cmi approved these changes

2023-08-31 10:25 UTC, merged